spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: new_password
    url: jdbc:postgresql://localhost:5432/postgres
    jpa:
      genegate-ddl: true
    hibernate:
      ddl-auto: update

